name=SoftI2C_VPORT
version=1.0.0
author=asa
maintainer=asa
sentence=Ultra lightweight VPORT software I2C for tinyAVR 0/1 series
paragraph=Minimal bit-bang I2C using VPORT register for ATtiny402/404 and other megaAVR 0/1 series devices.
category=Communication
architectures=megaavr